//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3.1-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Sql.g4 by ANTLR 4.5.3.1-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace sdlife.web.Models.SqlAntlr.Details {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SqlParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3.1-SNAPSHOT")]
[System.CLSCompliant(false)]
public interface ISqlVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>Parenthesis</c>
	/// labeled alternative in <see cref="SqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesis([NotNull] SqlParser.ParenthesisContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="SqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot([NotNull] SqlParser.NotContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>SingleOperator</c>
	/// labeled alternative in <see cref="SqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleOperator([NotNull] SqlParser.SingleOperatorContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Between</c>
	/// labeled alternative in <see cref="SqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBetween([NotNull] SqlParser.BetweenContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Contains</c>
	/// labeled alternative in <see cref="SqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContains([NotNull] SqlParser.ContainsContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>AndOr</c>
	/// labeled alternative in <see cref="SqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndOr([NotNull] SqlParser.AndOrContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Function</c>
	/// labeled alternative in <see cref="SqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] SqlParser.FunctionContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Number</c>
	/// labeled alternative in <see cref="SqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] SqlParser.NumberContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>BinaryFunction</c>
	/// labeled alternative in <see cref="SqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryFunction([NotNull] SqlParser.BinaryFunctionContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>ExpressionParenthesis</c>
	/// labeled alternative in <see cref="SqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionParenthesis([NotNull] SqlParser.ExpressionParenthesisContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Binary</c>
	/// labeled alternative in <see cref="SqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary([NotNull] SqlParser.BinaryContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="SqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] SqlParser.StringContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Date</c>
	/// labeled alternative in <see cref="SqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDate([NotNull] SqlParser.DateContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.run"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRun([NotNull] SqlParser.RunContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicate([NotNull] SqlParser.PredicateContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] SqlParser.ExpressionContext context);
}
} // namespace sdlife.web.Managers.SqlAntlr
